---
- name: provision platformio ide
  hosts: all
  become: true
  become_method: sudo

  roles:
  - centos.base
  - ansible-role-mate-desktop
  - ansible-role-atom
  - ansible-role-mosquitto
  - ansible-role-nodered
